Remove "experiments" block, changes in variables, minor edits in examples
aws-ia/terraform-aws-cloudwan pull request #13
Opened 2022-10-24 13:45 UTC by pablo19sc

- Removed "experiments" block and update required_version to >= 1.3.0
- Updated variables to have "create_global_network" inside "global_network" block
- Minor updates in examples

2022-10-24 13:46 UTC, pablo19sc commented
Passed tests:

![test2](https://user-images.githubusercontent.com/76947510/197540793-7be8faba-7a07-4888-85db-db335b0fc7c1.png)
![test1](https://user-images.githubusercontent.com/76947510/197540781-be9cbd9d-27f3-4f28-a50f-3376fd62bd5f.png)

2023-01-17 16:07 UTC, drewmullen requested changes
lg but 1 small change

2023-01-17 16:07 UTC, drewmullen commented on variables.tf
> +  - `description` = (any) Core Network's policy in JSON format. It is recommended the use of the [Core Network Document data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/
```suggestion
- `policy` = (any) Core Network's policy in JSON format. It is recommended the use of the [Core Network Document data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/networkmanager_core_network_policy_document)
```

2023-01-20 14:14 UTC, drewmullen approved these changes
looks like the example docs are a little fuzzy on which version is being used but i think thats because the v1 hasnt shipped yet

2023-01-24 17:14 UTC, drewmullen approved these changes

2023-01-24 17:14 UTC, merged